#!/bin/env ruby
# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Environment variables (ENV['...']) are set in the file config/application.yml.
# See http://railsapps.github.com/rails-environment-variables.html
# puts 'SETTING UP DEFAULT USER LOGIN'
# user = User.create! :name => ENV['ADMIN_NAME'], :email => ENV['ADMIN_EMAIL'].dup, :password => ENV['ADMIN_PASSWORD'].dup, :password_confirmation => ENV['ADMIN_PASSWORD'].dup, :confirmed_at => Time.now.utc
# user.confirm!
# puts 'New user created: ' << user.name
# user2 = User.create! :name => "test", :email => "pvskisteak@yahoo.com", :password => "123456", :password_confirmation => "123456", :confirmed_at => Time.now.utc
# user2.confirm!
# puts 'New user created: ' << user2.name
# user.add_role :admin

# create content for tutorials with below

Package.destroy_all
Tutorial.destroy_all
Topic.destroy_all
BlankQuiz.destroy_all
Transcript.destroy_all

packages = [ 
	{:price => 9.99, :title => 'Introduction to Excel', :description => 'This comprehensive screencast tutorial, with numerous template and example Microsoft Excel files included as downloads, gives a Beginner an overview of the most popular business software program in the world. Become productive with Excel after finishing our Introduction to Excel lessons, which are approximately 10-25 minutes each episode.  We have designed our Beginner Excel course to be as frictionless as possible, with detailed walk throughs and examples discussed.  Watch the episodes first, then give it a try yourself.  Take advantage of having reference material available 24 hours a day.', :length => 180},
	{:price => 9.99, :title => 'Intermediate Tutorials', :description => 'Take your Excel skills to the next level with these useful lessons.  The tutorial is approximately two hours long, giving you a detailed and easy to follow explanation of complex material.', :length => 120}
]



tutorials = [
	{:package_id => 1, :price => 0, :title => "Starting From Scratch", :description => "First steps to getting started with Microsoft Excel.  This episode starts out assuming you know very little about Excel, with items such as opening Excel for the first time, but quickly moves on to more advanced topics such as keyboard shortcuts.  A great episode to get an overview of Excel and how it can be used.", :length => 18, :video_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_starting_from_scratch.m4v", :excel_path => 'http://s3.amazonaws.com/officescholar/intro_to_excel_1_starting_from_scratch.xlsx'},
	{:package_id => 1, :price => 0, :title => "Worksheets", :description => "See how to manipulate data, modify the structure of a worksheet and perform basic tasks to learn the ins and outs of an Excel worksheet, the foundation of the tool.", :length => 16, :video_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_worksheets.m4v", :excel_path => 'http://s3.amazonaws.com/officescholar/intro_to_excel_2_worksheets.xlsx'},
	{:package_id => 1, :price => 0, :title => "Intro to Formulas", :description => "First glimpse into using Excel as a powerful calculator and analysis tool. We begin with manually operations and end with built-in functions.", :length => 11, :video_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_intro_to_formulas.m4v", :excel_path => 'http://s3.amazonaws.com/officescholar/intro_to_excel_3_intro_to_formulas.xlsx'},
	{:package_id => 1, :price => 0, :title => "Intro to Formatting", :description => "See how to customize the look and feel of your Excel worksheets.", :length => 14, :video_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_intro_to_formatting.m4v", :excel_path => 'http://s3.amazonaws.com/officescholar/intro_to_excel_4_intro_to_formatting.xlsx'},
	{:package_id => 1, :price => 0, :title => "Charts", :description => "First look into charts gives basic overview of various chart types available in Excel as well specific instructional walk-throughs building column, pie, line and sparkline charts from scratch.", :length => 23, :video_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_charts.m4v", :excel_path => 'http://s3.amazonaws.com/officescholar/intro_to_excel_5_charts.xlsx'},
	{:package_id => 1, :price => 0, :title => "Sorting and Filtering", :description => "Both sorting and filtering are demonstrated on example data tables, along with multiple conditions and the VLOOKUP function for referencing data in other locations based on a matched value.", :length => 11, :video_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_sorting_and_filtering.m4v", :excel_path => 'http://s3.amazonaws.com/officescholar/intro_to_excel_6_sorting_and_filtering.xlsx'},
	{:package_id => 1, :price => 0, :title => "Pivot Tables", :description => "Using data set from the 2012-2013 NFL Football season, see how to create, modify, format and sort a pivot table.  Also cover Pivot Table filters using Excel 2010's new Slicer feature for a more visual filter interface.", :length => 13, :video_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_pivot_tables.m4v", :excel_path => 'http://s3.amazonaws.com/officescholar/intro_to_excel_7_pivot_tables.xlsx'},
	{:package_id => 1, :price => 0, :title => "Printing", :description => "Walk through printing a document in Excel including overviews on print preview, headers and footers, print areas and repeating a single row as a column heading for multiple pages.", :length => 10, :video_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing.m4v", :excel_path => 'http://s3.amazonaws.com/officescholar/intro_to_excel_8_printing.xlsx'}
	# {:package_id => 1, :price => 0, :title => "National Sales Team", :description => "Each of our weekly reports include a short screencast on how to view, modify and submit.  Contact Jeff Hoosay for any suggested changes.", :length => 37, :video_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing.m4v", :excel_path => 'http://s3.amazonaws.com/officescholar/intro_to_excel_8_printing.xlsx'},
	# {:package_id => 1, :price => 0, :title => "Northwest Sales Team", :description => "Northwest only sales team data.  Walk through of monthly requirements.  Contact Jeff Hoosay for any suggested changes.", :length => 27, :video_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing.m4v", :excel_path => 'http://s3.amazonaws.com/officescholar/intro_to_excel_8_printing.xlsx'}
]

Tutorial.create tutorials

@tutorial_id = Tutorial.first.id

topics = [
	{:tutorial_id => @tutorial_id, :title => "Intro", :description => "Introduction and overview of Microsoft Excel with a discussion on uses.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_starting_from_scratch_intro.m4v"},
	{:tutorial_id => @tutorial_id, :title => "Accessing Excel", :description => "Learn how to open Excel multiple ways including creating a desktop shortcut.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_starting_from_scratch_accessing_excel.m4v"},	
	{:tutorial_id => @tutorial_id, :title => "Navigation", :description => "Explanation of Excel windows and introduction to navigating the ribbon interface.", :length => 5, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_starting_from_scratch_navigating_excel.m4v"},
	{:tutorial_id => @tutorial_id, :title => "Open and Save", :description => "Walk through discussing how to open a file in Excel from within the program, how to save a file and how to close out of the program.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_starting_from_scratch_opening_saving_closing.m4v"},
	{:tutorial_id => @tutorial_id, :title => "Keyboard Shortcuts", :description => "Useful keyboard shortcuts that will save you a ton of time and effort over the long haul.", :length => 4, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_starting_from_scratch_shortcuts.m4v"},
	{:tutorial_id => @tutorial_id, :title => "File Types", :description => "Learn the importance of file formats in Microsoft Office products with a focus on Excel.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_starting_from_scratch_file_types.m4v"},
	{:tutorial_id => @tutorial_id, :title => "Help Feature", :description => "When you cannot solve a problem on your own or find yourself stuck, turn to the help feature.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_starting_from_scratch_help_feature.m4v"},
	{:tutorial_id => @tutorial_id, :title => "Conclusion", :description => "Wrap up with conclusion and takeaways from the Starting from Scratch lessons.", :length => 0, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_starting_from_scratch_conclusion.m4v"},
	
	{:tutorial_id => (@tutorial_id+1), :title => "Intro", :description => "Overview of Excel's Worksheet and discussion on topics covered in the related episodes.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_worksheets_intro.m4v"},
	{:tutorial_id => (@tutorial_id+1), :title => "Creating a Worksheet", :description => "Tutorial covers creating a new worksheet in Excel and related topics.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_worksheets_creating_a_worksheet.m4v"},
	{:tutorial_id => (@tutorial_id+1), :title => "Entering Data", :description => "Learn various techniques for entering data in Excel.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_worksheets_entering_data.m4v"},
	{:tutorial_id => (@tutorial_id+1), :title => "Selecting Data", :description => "Instruction on how to select cells and ranges of cells in Excel.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_worksheets_selecting_data.m4v"},
	{:tutorial_id => (@tutorial_id+1), :title => "Copying and Pasting", :description => "More in depth overview of Excel's copy and paste special functionality.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_worksheets_copy_and_paste_special.m4v"},
	{:tutorial_id => (@tutorial_id+1), :title => "Manipulating Data", :description => "Screencast covers techniques for modifying data in Excel.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_worksheets_manipulating_data.m4v"},
	{:tutorial_id => (@tutorial_id+1), :title => "Rows and Columns", :description => "More in depth overview of Excel's rows and columns structure.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_worksheets_rows_and_columns.m4v"},
	{:tutorial_id => (@tutorial_id+1), :title => "Grouping and Hiding", :description => "Learn how to group and hide rows and columns in Excel.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_worksheets_grouping_and_hiding.m4v"},
	{:tutorial_id => (@tutorial_id+1), :title => "Conclusion", :description => "Final thoughts on worksheets for the introductory series.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_worksheets_conclusion.m4v"},

	{:tutorial_id => (@tutorial_id+2), :title => "Overview and Uses", :description => "Introduction to formulas and functions in Excel with examples of common uses.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formulas_intro.m4v"},
	{:tutorial_id => (@tutorial_id+2), :title => "Manual Calculations", :description => "Learn the fundamentals of executing an Excel formula by first learning manual calculations.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formulas_manual_calculations.m4v"},
	{:tutorial_id => (@tutorial_id+2), :title => "Functions", :description => "First look at Excel's built in functions including explanation on setting up functions in Excel.", :length => 4, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formulas_intro_to_functions.m4v"},
	{:tutorial_id => (@tutorial_id+2), :title => "IF Statements", :description => "Preview to IF statements in Excel, which is a powerful function used often.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formulas_if_statement.m4v"},
	{:tutorial_id => (@tutorial_id+2), :title => "Conclusion", :description => "Concluding thoughts on Excel's formulas and functions.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formulas_if_statement.m4v"},

	{:tutorial_id => (@tutorial_id+3), :title => "Intro", :description => "Overview of formatting in Excel.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formatting_intro.m4v"},
	{:tutorial_id => (@tutorial_id+3), :title => "Formatting Cells", :description => "The first part of learning how to format in Excel is mastering cell formats.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formatting_formatting_cells.m4v"},
	{:tutorial_id => (@tutorial_id+3), :title => "Formatting Text", :description => "Introduction to number formats and font formatting options.", :length => 4, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formatting_formatting_text.m4v"},
	{:tutorial_id => (@tutorial_id+3), :title => "Alignment", :description => "Learn various techniques for aligning elements in Excel.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formatting_alignment.m4v"},
	{:tutorial_id => (@tutorial_id+3), :title => "Formatting Tips", :description => "Several tricks everyone should be using in Excel to save time with formatting.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formatting_tips_and_tricks.m4v"},
	{:tutorial_id => (@tutorial_id+3), :title => "Conclusion", :description => "Takeaways from this introduction to formatting in Excel.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_formatting_conclusion.m4v"},

	{:tutorial_id => (@tutorial_id+4), :title => "Chart Types", :description => "Overview of chart types offered in Excel.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_charts_intro.m4v"},
	{:tutorial_id => (@tutorial_id+4), :title => "Column Chart", :description => "Step-by-step tutorial on building a column chart with example data.", :length => 9, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_charts_column_chart.m4v"},
	{:tutorial_id => (@tutorial_id+4), :title => "Pie Chart", :description => "Watch as Pat creates a pie chart with sample data from scratch.", :length => 6, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_charts_pie_chart.m4v"},
	{:tutorial_id => (@tutorial_id+4), :title => "Line Chart", :description => "Tutorial on creating a line chart in Excel.", :length => 4, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_charts_line_chart.m4v"},
	{:tutorial_id => (@tutorial_id+4), :title => "Sparklines", :description => "See how to creat column chart sparklines and line chart sparklines easily.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_charts_sparklines.m4v"},
	{:tutorial_id => (@tutorial_id+4), :title => "Conclusion", :description => "Takeaway from our introduction to charts lessons.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_charts_conclusion.m4v"},

	{:tutorial_id => (@tutorial_id+5), :title => "Intro", :description => "Overview of sorting and filtering in Excel.", :length => 0, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_sorting_and_filtering_intro.m4v"},
	{:tutorial_id => (@tutorial_id+5), :title => "Sorting", :description => "Various data sorts are performed on a sample table.", :length => 5, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_sorting_and_filtering_sorting.m4v"},
	{:tutorial_id => (@tutorial_id+5), :title => "Filtering", :description => "Example data table is filtered using Excel's auto filters.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_sorting_and_filtering_filtering.m4v"},
	{:tutorial_id => (@tutorial_id+5), :title => "VLOOKUP", :description => "Use the VLOOKUP function to reference data in other tables based on a matched value.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_sorting_and_filtering_vlookup.m4v"},
	{:tutorial_id => (@tutorial_id+5), :title => "Conclusion", :description => "Use the VLOOKUP function to reference data in other tables based on a matched value.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_sorting_and_filtering_conclusion.m4v"},

	{:tutorial_id => (@tutorial_id+6), :title => "Uses", :description => "When to use a pivot table and why they can be helpful.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_pivot_table_intro.m4v"},
	{:tutorial_id => (@tutorial_id+6), :title => "Creating a Pivot Table", :description => "How to select data and create a pivot table.", :length => 4, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_pivot_table_creating_a_pivot_table.m4v"},
	{:tutorial_id => (@tutorial_id+6), :title => "Rearranging", :description => "Overview on how to quickly modify the layout of a pivot table.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_pivot_tables_rearraning_pivot_tables.m4v"},
	{:tutorial_id => (@tutorial_id+6), :title => "Formatting", :description => "Demonstration showing how to format a pivot table.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_pivot_tables_formatting_pivot_tables.m4v"},
	{:tutorial_id => (@tutorial_id+6), :title => "Sorting and Filtering", :description => "Covers sorting inside a pivot table as well as filtering with the Slicer.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_pivot_tables_sorting_and_filtering_pivot_tables.m4v"},
	{:tutorial_id => (@tutorial_id+6), :title => "Conclusions", :description => "Concluding thoughts on the introductory pivot table lessons.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_pivot_tables_conclusion.m4v"},

	{:tutorial_id => (@tutorial_id+7), :title => "Intro and Print Preview", :description => "Learn the shortcut for quickly previewing an excel document.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_intro_and print_preview.m4v"},
	{:tutorial_id => (@tutorial_id+7), :title => "Page Layout and Setup", :description => "Walk through sections of the page setup.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_page_layout.m4v"},
	{:tutorial_id => (@tutorial_id+7), :title => "Headers and Footers", :description => "See how to modify the header and footer.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_headers_and_footers.m4v"},
	{:tutorial_id => (@tutorial_id+7), :title => "Page Breaks", :description => "Watch a demonstration on inserting and removing page breaks.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_page_breaks.m4v"},
	{:tutorial_id => (@tutorial_id+7), :title => "Printing Selected Areas", :description => "How to print selected cell ranges and areas of a spreadsheet and a guide on repeating rows as headers.", :length => 2, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_printing_selected_area.m4v"},
	{:tutorial_id => (@tutorial_id+7), :title => "Conclusion", :description => "Use a single row as the column header on multiple pages by repeating it.", :length => 1, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_conclusion.m4v"}

	# {:tutorial_id => (@tutorial_id+8), :title => "Weekly Pipeline Summary by Region", :description => "Learn the shortcut for quickly previewing an excel document.", :length => 7, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_intro_and print_preview.m4v"},
	# {:tutorial_id => (@tutorial_id+8), :title => "Forecast and Near-term Demand", :description => "Walk through sections of the page setup.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_page_layout.m4v"},
	# {:tutorial_id => (@tutorial_id+8), :title => "Compiled Accounts Receivable", :description => "See how to modify the header and footer.", :length => 8, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_headers_and_footers.m4v"},
	# {:tutorial_id => (@tutorial_id+8), :title => "Travel Expenses", :description => "Watch a demonstration on inserting and removing page breaks.", :length => 23, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_page_breaks.m4v"},
	# {:tutorial_id => (@tutorial_id+8), :title => "Printing Weekly Reports", :description => "How to print selected cell ranges and areas of a spreadsheet and a guide on repeating rows as headers.", :length => 4, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_printing_selected_area.m4v"},
	# {:tutorial_id => (@tutorial_id+8), :title => "Sorting and Filtering Reports", :description => "Use a single row as the column header on multiple pages by repeating it.", :length => 19, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_conclusion.m4v"},
	# {:tutorial_id => (@tutorial_id+8), :title => "Data Analysis and Charts", :description => "Use a single row as the column header on multiple pages by repeating it.", :length => 13, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_conclusion.m4v"},
	# {:tutorial_id => (@tutorial_id+8), :title => "Formulas Used in Reports", :description => "Use a single row as the column header on multiple pages by repeating it.", :length => 6, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_conclusion.m4v"},

	# {:tutorial_id => (@tutorial_id+9), :title => "Financial Models Explained", :description => "Learn the shortcut for quickly previewing an excel document.", :length => 7, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_intro_and print_preview.m4v"},
	# {:tutorial_id => (@tutorial_id+9), :title => "Standard R&F Forms", :description => "Walk through sections of the page setup.", :length => 3, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_page_layout.m4v"},
	# {:tutorial_id => (@tutorial_id+9), :title => "Quota Standings", :description => "See how to modify the header and footer.", :length => 8, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_headers_and_footers.m4v"},
	# {:tutorial_id => (@tutorial_id+9), :title => "THE BOSS REPORT", :description => "All reports for BOSS that you can handle.  Starts with weekely submittal process and ends with his favorite data analysis techniques.", :length => 27, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_page_breaks.m4v"},
	# {:tutorial_id => (@tutorial_id+9), :title => "Process of Expenses", :description => "How to print selected cell ranges and areas of a spreadsheet and a guide on repeating rows as headers.", :length => 4, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_printing_selected_area.m4v"},
	# {:tutorial_id => (@tutorial_id+9), :title => "Meeting Logging", :description => "Use a single row as the column header on multiple pages by repeating it.", :length => 19, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_conclusion.m4v"},
	# {:tutorial_id => (@tutorial_id+9), :title => "Advanced Data Analysis", :description => "Use a single row as the column header on multiple pages by repeating it.", :length => 13, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_conclusion.m4v"},
	# {:tutorial_id => (@tutorial_id+9), :title => "Schedule of Leans", :description => "Use a single row as the column header on multiple pages by repeating it.", :length => 6, :topic_path => "http://s3.amazonaws.com/officescholar/intro_to_excel_printing_conclusion.m4v"}
]


Topic.create topics

@topic_id = Topic.first.id

transcripts = [
	{:topic_id => (@topic_id), :content => "Hello. Welcome to OfficeScholar. My name is Pat Vihtelic. In this first episode of Introduction to Excel, I’m going to assume you know very little about the program. We’re going to start from scratch. The one thing I will assume is that you already have Microsoft Excel 2010 installed on your computer. 
	If you’re brand new to Excel, one of the first things you may be asking yourself is, 'What exactly is it?' From a high level, I think Excel helps you do four things. It helps with data organization, performing calculations, displaying that data in charts and graphs, and of course automating tasks that may have been manual in the past. 
	Let’s take a look at a couple of examples to help put some of these concepts into contexts. There are tons of use cases from Microsoft Excel. Just to paint the picture, let me throw out a few examples, someone might use Excel as a database to store employee records to keep track of headcount. They might also use Excel to set up forms to be used in some type of survey. 
	Here we’re looking at a financial analysis. This analysis is completely fictional. It’s a projected P&L, profit and lost statement for OfficeScholar. Not only are we relying on Excel to help us store some historical data here from revenue down to net income, but we’re also using its formulas and functions to help us project revenue and net income in the future. 
	Here for example, we’re using this revenue growth assumption to drive a revenue estimate for 2013. Here we’re using the sum function to get the total for our operating costs. 
	On the right here, we’re also using a chart to illustrate our data. If I change the assumption, instead of having to manually go back and change all these figures in the chart, Excel automatically updates. I can go from a 90% revenue growth rate to a 50% revenue growth rate, and quickly see the results."},
	{:topic_id => (@topic_id+1), :content => "Now that you’ve seen how someone might be using Microsoft Excel, let’s talk about how to access it and open it up. If it were my first time opening up Microsoft Excel, what I would do is go down to the Start Menu in the bottom left-hand corner of the screen. Go to All Programs, then Microsoft Office, then Microsoft Excel 2010. If I want to get to it faster, what I can do is add a shortcut icon to my desktop. Let’s go to the same route. Go to All Programs, Microsoft Office. This time I want you to right click on Microsoft Excel. Go to Send to, and then Desktop (create shortcut). Now, we can double click on this icon, and open up Microsoft Excel. 
	If we want to get to a specific file quicker, we can do the same thing. Let’s go to out Start Menu. Notice here, Microsoft Excel was added because I’ve been using it recently. Let’s hover over a recent file. Click on it, drag it to the desktop. Now I can double click on this file to open it up."},
	{:topic_id => (@topic_id+2), :content => "Learning how to navigate Microsoft Excel can be half the battle on being productive with it. Let’s get started. I’m going to go ahead and open up a blank Microsoft Excel spreadsheet. We’re going to focus on the top part of the spreadsheet and what excel refers to as the ribbon interface. It’s broken up into different tabs, with each tab containing a different collection of subcategories. 
	Let’s start with the File Tab on the far left. The File Tab is the background information for your file. You’ll notice that it’s the only tab that doesn’t have the spreadsheet in the main part of its view. The areas that you will be using the most in the file tab are Save, Save As, Open, Close, Recent, and Print. 
	The Home Tab is primarily made up of formatting tools. You can do things like paste, cut, copy, and use the format painter. Notice when I hover an icon, excel gives me a brief description of what that icon does, and at times gives me a keyboard shortcut to get to that action quicker. If you’re coming up the curve on excel, it’s a good idea to go through each of these icons. Hover over it, see what it does, and then it will make it that much easier to use it in the future. 
	Other subcategories here under the Home Tab are the Font section, Alignment section, Number section where I can change data types from say a dollar sign to percentage, Styles, Cells, and Editing. The only thing I’ll point out here on the right is Conditional Formatting. We’ll get into that later. What it does, let’s say for example you have a spreadsheet full of numbers, and you want to make all of the negative numbers on that spreadsheet red, you can do that through Conditional Formatting. 
	The Insert Tab does exactly what you think it would do. It helps you insert objects directly into your spreadsheet. If you had a picture or an image, or if you wanted to insert a column chart or a pie chart, or a textbox, or a header and footer, you can do that all through the Insert Tab. 
	The Page Layout Tab is something that I primarily use right before printing. However, there’s a lot of other things you can do with it. For example under Themes, you could use Excel’s prebuilt themes to help you design a color scheme for your spreadsheet. Preparing for printing has a lot to do with Page Setup, so you can click on this pop out for more options, but you can do things like changing margin, change the orientation from, say, portrait to landscape. 
	Other things you can do on the Page Layout Tab are if you’ve inserted objects, you can bring them forward, send them backward if they’re overlapping, and you can align them. 
	The Formulas Tab helps you with Microsoft’s formulas and functions. It has really good documentation that helps explain what the formulas do. They’ve also gone to the trouble of categorizing the formulas into different categories such as Financial, Text, and Math. They also have what they call Formula Auditing Tools. This is to help you troubleshoot when you run into errors with your formulas. 
	The Data Tab is made up of Excel’s data analysis tools. From somewhat basic database tools such as sorting things alphabetically or in order. You can also filter things. Then more advance tools such as What-If Type Analysis. 
	The Review Tab has things like Spell Check, adding a comment into a spreadsheet, or protecting your worksheets, so adding a password if you don’t want to share it with everyone. 
	Finally, the view tab. Right now we’re in what excel refers to as the normal view. You can change to a page layout view or to full screen. I sometimes use full screen when demoing things on OfficeScholar. Then you just hit escape to get out of the full screen view to go back to normal. You can also take off gridlines under the View. I sometimes do this when working on my own. I think it helps clean up the View a little bit, but for demonstration purposes, I like to keep the gridlines on. 
	The last thing I’d like to point out in the ribbon interface is the zoom. Right now, we’re at a 100% zoom. I sometimes will use a higher zoom for demo purposes, but primarily, I’m using a 100% zoom when I’m working. 
	That’s a quick overview of what the ribbon interface does. It’s best for you to go through, and click through each of the icons, and familiarize yourself with where everything is because it will make going forward that much easier."},
	{:topic_id => (@topic_id+3), :content => "Now that we have our bearing straight with Excel’s navigation, let’s talk about opening, saving, and closing the file. 
	I have a blank Microsoft Excel spreadsheet open. The file that I would like to open up is located on my desktop in a folder called the OfficeScholar Files. To open up that file from within the spreadsheet, I can go to file, and then open, desktop, we’ll go down to OfficeScholar files, double click this file folder, and I’m going to open up this Intro to Excel One: Starting from Scratch, which is a file that you should all have. I can either double click this file, or select it by clicking it once, and then hitting open. Now we have the file open. 
If I intend to make changes to this file, it’s my philosophy that you should save up another version of it. That way, if you make a mistake, you always have the original copy of the file. To save another version, use the Save As tool. We go to File, and then Save As. I’ll just type in v2 at the end of the filename, which is short for version two, hit save. Now if I made a mistake like deleting revenue growth, and if I saved this by going to File, and then Save, I still have the original copy of the file which is in the correct format. 
	Another option you have is to shorten the autosave time in excel. By default, Microsoft Excel automatically saves every 10 minutes. I’ve changed mine to five minutes. Let me show you how. Go to File, and then Options, and then click on Save, and then where it says Save AutoRecover Information every, yours should say 10 minutes, change it to five minutes. Then hit OK."},
	{:topic_id => (@topic_id+4), :content => "The next thing I’d like to cover are basic keyboard shortcuts for Microsoft Excel. These aren’t required to use Excel, but they will make you a lot faster and much more productive. Keyboard shortcuts in Excel are designed to save you time. You’d be amazed at how much more efficient you can be when you’re relying on just your keyboard, and not having to go back and forth clicking your mouse to get things done. 
	On the left side of the spreadsheet, I laid out commonly used Microsoft excel keyboard shortcuts. On the right side, I have a step by step guide to navigating the ribbon interface using just your keyboard, which we’ll discuss in just a second. I also have a link to a free guide from Microsoft excel, which is a much more extensive guide to keyboard shortcuts. 
	Let me quickly demonstrate how much faster it is to use keyboard shortcuts versus using your mouse. Let me just type out some demo data here. All we’re going to do is copy and paste this number 1,000 in this text that says blue. If I were to copy this number 1,000, I would right click on it. Go to copy, select the cell where I’d like to paste, right click, and then hit paste. 
	Let me delete that, and I’ll show you how to do that with just your keyboard, so not touching your mouse at all. You can use your arrow keys to navigate on the keyboard. I’m going to hold Ctrl and then hit C in the cell that I’d like to copy. Go to the cell where I’d like to paste. Hold Ctrl and then hit V. I can just hold Ctrl, hit C, and then hold Ctrl, and hit V. 
	To cut using my mouse, I would right click, and then go to cut. I’d select the cell where I’d like to go. Then right click, and go to paste. It removed it from this cell, and put it in the destination cell. Let me hit Ctrl + Z to undo that. 
	Let me show you how to do that with just the keyboard. I’ll hold Ctrl, and then hit X. Go to the cell where I’d like to paste it. Hold Ctrl, and then hit V. I’ll hit Ctrl and Z to undo that. Just to demonstrate it one more time. If I hit escape, it will unselect this cell. Go over this cell. Hold Ctrl and hit X. Go to the destination cell, hold Ctrl, and then hit V. 
	Other things I could do to this sample data is quickly bold it by holding Ctrl, and hit B. I can underline it by holding Ctrl, and hitting U. That saves me the trouble of grabbing my mouse, and going over and hitting these icons up here, or right clicking and going through the format cells window. I’m going to hold Ctrl, and then hit Z to undo that. 
Now let’s take a look at the ribbon interface. To access the ribbon interface, you first need to hit Alt on your keyboard. This brings up what Microsoft Excel refers to as the Hotkeys. These are basically shortcuts to each of these tabs. If I want to go to the View tab, I would hit W. If I want to bring up Zoom, I hit Q, and I can change the zoom, and hit OK.
 If I want to bring up the Formulas Tab, I’ll hit Alt which brings up all the tab hotkeys. M for formulas, then let’s hit G for Math and Trig. Then I can hit escape to get out of that. Escape again to go back. If I want to go to the home tab, I’ll hit H. If I wanted to change the font, I’ll hit FF, and then I can change the font directly from here. 
You can see how much time this would save you especially if you’re working all day in Excel."},
	{:topic_id => (@topic_id+5), :content => "The first thing to know about File Types in excel 2010 is that it matters. What I mean by that is that excel is unable to open certain types of files. Excel 2010’s files end in that xlsx, so its file name .xlsx, which is the same file format that was used in Excel 2007. 
Excel is unable to open other types. For example, Office 2010 word documents end in .x. Excel cannot open that. Excel can also not open other file types such as PDFs, which end in .pdf, or images which may end in .img. In saving in excel, it default’s to the correct file type, so you don’t have to think too much about it. 
I’m going to go ahead and open up a blank Microsoft Excel spreadsheet. You’ve already seen how to save as. You can go to the file tab, and then Save As, or simply hit F12 on your keyboard. That brings up the Save As window. What I wanted to point out here was the Save As type. Excel automatically assumes that you’re going to want to save it as a .xlsx. That’s this Excel workbook. If I wanted to change the file to be compatible with ’97 to 2003 Excel, I can simply add .xls, or I can go to the save as type dropdown, and select Excel ’97 to 2003 Workbook. 
If I do save it as a .xls, just note that you’re going to lose some of the functionality that .xlsx has. You really shouldn’t be changing file formats unless you have to. The only reason you’re going to want to change a .xls is if you’re working with a colleague or another company that does not have Excel 2007 or higher. 
That’s a basic overview of file formats. Hopefully, that won’t cause too much trouble for you, but it’s always something you should be aware of when working on an Excel worksheet."},
	{:topic_id => (@topic_id+6), :content => "The last section to discuss in our Getting Started Tutorial is the Help Feature. Before turning to the Help Feature when you find yourself stuck, I definitely encourage you to explore a little bit. Not only might you find the answer to your problem, but you’re also probably going to learn something else along the way. 
	Let’s say for instance I wanted to change cell B5. Right now it’s currently formatted as a percentage. Let’s say I would like to change it to a currency, and I don’t know how to do that. What I can do is hit F1 on my keyboard, so that’s now brought up the Excel Help window. I can simply type currency here. Hit enter to search, and you’ll see the first result here looks pretty promising. Clicking in, it looks like if I follow these directions, I should be able to format that number as a currency. 
	If you can’t find the answer to your problem through Microsoft’s Help Feature, I definitely encourage you to try searching on Google or on Microsoft Bing. It’s really likely that someone has run into the exact same problem that you’re facing. "},
	{:topic_id => (@topic_id+7), :content => "That concludes the Getting Started Tutorial, which is the first chapter in our Introduction to Excel Series. What are some of the takeaways here? Definitely, try replicating everything that I just download. Open up excel, play around with the Ribbon Interface, and try to use some of the basic keyboard shortcuts that we went over. 
Check out our next episode. We will be taking our first look at worksheets."},
	{:topic_id => (@topic_id+8), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+9), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+10), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+11), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+12), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+13), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+14), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+15), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+16), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+17), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+18), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+19), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."},
	{:topic_id => (@topic_id+20), :content => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum."}
]


blank_quizzes = [
	{:tutorial_id => (@tutorial_id), :title => "Level I - Getting Started", :description => "You need to be able to open a file, add a worksheet, modify a worksheet name, use save, open and close as well as copy and paste.", :url => 'http://s3.amazonaws.com/officescholar/starting_from_scratch_quiz.xlsx'},
	{:tutorial_id => (@tutorial_id+1), :title => "Level I - Worksheets", :description => "In this Skill Assessment, we will copy and enter data as well as modify the structure of a worksheet by adding rows and columns.", :url => 'http://s3.amazonaws.com/officescholar/worksheets_quiz.xlsx'},
	{:tutorial_id => (@tutorial_id+2), :title => "Level I - Formulas", :description => "In this Skill Assessment, you will be tested on manual calculations including addition, subtraction, multiplication and division.  Other areas covered include functions such as the COUNT(), SUM(), AVERAGE() and MEDIAN() as well as the IF() statement.", :url => 'http://s3.amazonaws.com/officescholar/formulas_quiz.xlsx'}
	# {:tutorial_id => (@tutorial_id+8), :title => "Report Templates and Graphs", :description => "In this Skill Assessment, you will be tested on manual calculations including addition, subtraction, multiplication and division.  Other areas covered include functions such as the COUNT(), SUM(), AVERAGE() and MEDIAN() as well as the IF() statement.", :url => 'http://s3.amazonaws.com/officescholar/formulas_quiz.xlsx'},
	# {:tutorial_id => (@tutorial_id+9), :title => "Weekly Team Data", :description => "In this Skill Assessment, you will be tested on manual calculations including addition, subtraction, multiplication and division.  Other areas covered include functions such as the COUNT(), SUM(), AVERAGE() and MEDIAN() as well as the IF() statement.", :url => 'http://s3.amazonaws.com/officescholar/formulas_quiz.xlsx'}
	# {:tutorial_id => 4, :title => "Intro to Formatting", :description => "See how to customize the look and feel of your Excel worksheets.", :url => 'http://s3.amazonaws.com/officescholar/intro_to_excel_4_intro_to_formatting.xlsx'},
	# {:tutorial_id => 5, :title => "Charts", :description => "First look into charts gives basic overview of various chart types available in Excel as well specific instructional walk-throughs building column, pie, line and sparkline charts from scratch.", :url => 'http://s3.amazonaws.com/officescholar/intro_to_excel_5_charts.xlsx'},
	# {:tutorial_id => 6, :title => "Sorting and Filtering", :description => "Both sorting and filtering are demonstrated on example data tables, along with multiple conditions and the VLOOKUP function for referencing data in other locations based on a matched value.",:url => 'http://s3.amazonaws.com/officescholar/intro_to_excel_6_sorting_and_filtering.xlsx'},
	# {:tutorial_id => 7, :title => "Pivot Tables", :description => "Using data set from the 2012-2013 NFL Football season, see how to create, modify, format and sort a pivot table.  Also cover Pivot Table filters using Excel 2010's new Slicer feature for a more visual filter interface.", :url => 'http://s3.amazonaws.com/officescholar/intro_to_excel_7_pivot_tables.xlsx'},
	# {:tutorial_id => 8, :title => "Printing", :description => "Walk through printing a document in Excel including overviews on print preview, headers and footers, print areas and repeating a single row as a column heading for multiple pages.", :url => 'http://s3.amazonaws.com/officescholar/intro_to_excel_8_printing.xlsx'}

]

Package.create packages
Transcript.create transcripts
BlankQuiz.create blank_quizzes